<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPHjbivh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPHjbivh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPHjbivh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPHjbivh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPHjbivh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PHjbivh',
    'container.build_id' => '736da42c',
    'container.build_time' => 1569819068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPHjbivh');
